theme: jekyll-theme-minimal
title: Ying Li
description: Data Science Life Cycle
logo: https://github.com/yingli/yingli/blob/main/assets/img/yingli.png
show_downloads: false


# Permalinks
permalink:        pretty


# Setup
tagline:          'DSLC'
url:              "http://yingli.github.io"
baseurl:          "/"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/yingli
