theme: jekyll-theme-minimal
remote_theme: poole / hyde

title: Ying Li
description: Hi

# Dependencies

# Permalinks
permalink:        pretty


# Setup
tagline:          'hello'
description:      'DSLC' 
url:              "http://yingli.github.io"
baseurl:          "/"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/yingli
