remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-slate
#remote_theme: poole/hyde
#remote_theme: mmistakes/so-simple-theme

title: Ying Li
description: Hi

# Dependencies

# Permalinks
permalink:        pretty


# Setup
tagline:          'hello'
description:      'DSLC' 
url:              "http://yingli.github.io"
baseurl:          "/"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/yingli
