#remote_theme: poole/hyde
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-slate

title: Ying Li
description: Portfolio

# Dependencies

# Permalinks
permalink:        pretty


# Setup
tagline:          'DSLC'
url:              "http://yingli.github.io"
baseurl:          "/"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/yingli/yingli
